tasks:
  - init: make build # runs during prebuild
    command: |
      cd ./dev
      docker-compose up -d
      bash ./populate.sh
      cd ../
      ./bin/perses -config ./dev/config.yaml
  - init: |
      export NG_CLI_ANALYTICS=ci
      npm install -g npm@7
      cd ./ui
      npm ci
    command: |
      export NG_CLI_ANALYTICS=ci
      cd ./ui
      npm run build
      npm start
    openMode: split-right
  
ports:
  - port: 3001
    onOpen: open-preview
  - port: 8080
    onOpen: ignore
  - port: 2379
    onOpen: ignore
  - port: 2380
    onOpen: ignore
