builds:
  - id: "perses"
    main: ./cmd/perses/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
      - PKG_LDFLAGS=github.com/perses/common/app
    ldflags:
      - "-s -w -X {{.Env.PKG_LDFLAGS}}.Version={{.Version}} -X {{.Env.PKG_LDFLAGS}}.Commit={{.Commit}} -X {{.Env.PKG_LDFLAGS}}.BuildTime={{.Date}}"
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - "perses"
    image_templates:
      - "docker.io/persesdev/perses:latest"
      - "docker.io/persesdev/perses:{{ .Tag }}"
      - "docker.io/persesdev/perses:v{{ .Major }}.{{ .Minor }}"
