version: 2.1
orbs:
  go: circleci/go@1.5.0
  node: circleci/node@4.2.0
jobs:
  test:
    docker:
    - image: circleci/golang:1.16
    - image: 'quay.io/coreos/etcd:v3.4.7'
      command:
      - /usr/local/bin/etcd
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
    steps:
      - checkout
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
          - go-mod-v1-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/home/circleci/go/pkg/mod"
      - run: make integration-test
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  main:
    jobs:
      - test:
          filters:
            tags:
              ignore: /.*/
